import { ROLES } from "./roles";

/**
 * Niveles de acceso.
 */
export const ACCESS_LEVELS = Object.freeze({
  TOTAL: "total",
  AREA: "area",
  PROPIO: "propio",
  LECTURA: "lectura",
  NINGUNO: "ninguno",
});

/**
 * Identificadores oficiales de los módulos.
 *
 * Estos nombres se utilizarán tanto en la matriz de permisos
 * como en el menú lateral.
 */
export const MODULES = Object.freeze({
  DASHBOARD: "dashboard",
  EMPLEADOS: "empleados",
  ASISTENCIA: "asistencia",
  CHECADAS_CRUDAS: "checadas_crudas",
  INCIDENCIAS: "incidencias",
  REPORTES: "reportes",
  DISPOSITIVOS: "dispositivos",
  HORARIOS: "horarios",
  USUARIOS_SISTEMA: "usuarios_sistema",
  AUDITORIA: "auditoria",
  CONFIGURACION: "configuracion",
});

/**
 * Matriz de permisos por rol.
 */
export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: {
    [MODULES.DASHBOARD]: ACCESS_LEVELS.TOTAL,
    [MODULES.EMPLEADOS]: ACCESS_LEVELS.TOTAL,
    [MODULES.ASISTENCIA]: ACCESS_LEVELS.TOTAL,
    [MODULES.CHECADAS_CRUDAS]: ACCESS_LEVELS.TOTAL,
    [MODULES.INCIDENCIAS]: ACCESS_LEVELS.TOTAL,
    [MODULES.REPORTES]: ACCESS_LEVELS.TOTAL,
    [MODULES.DISPOSITIVOS]: ACCESS_LEVELS.TOTAL,
    [MODULES.HORARIOS]: ACCESS_LEVELS.TOTAL,
    [MODULES.USUARIOS_SISTEMA]: ACCESS_LEVELS.TOTAL,
    [MODULES.AUDITORIA]: ACCESS_LEVELS.TOTAL,
    [MODULES.CONFIGURACION]: ACCESS_LEVELS.TOTAL,
  },

  [ROLES.RH_ADMIN]: {
    [MODULES.DASHBOARD]: ACCESS_LEVELS.TOTAL,
    [MODULES.EMPLEADOS]: ACCESS_LEVELS.TOTAL,
    [MODULES.ASISTENCIA]: ACCESS_LEVELS.TOTAL,
    [MODULES.CHECADAS_CRUDAS]: ACCESS_LEVELS.TOTAL,
    [MODULES.INCIDENCIAS]: ACCESS_LEVELS.TOTAL,
    [MODULES.REPORTES]: ACCESS_LEVELS.TOTAL,
    [MODULES.DISPOSITIVOS]: ACCESS_LEVELS.NINGUNO,
    [MODULES.HORARIOS]: ACCESS_LEVELS.TOTAL,
    [MODULES.USUARIOS_SISTEMA]: ACCESS_LEVELS.NINGUNO,
    [MODULES.AUDITORIA]: ACCESS_LEVELS.NINGUNO,
    [MODULES.CONFIGURACION]: ACCESS_LEVELS.NINGUNO,
  },

  [ROLES.SUPERVISOR]: {
    [MODULES.DASHBOARD]: ACCESS_LEVELS.TOTAL,
    [MODULES.EMPLEADOS]: ACCESS_LEVELS.AREA,
    [MODULES.ASISTENCIA]: ACCESS_LEVELS.AREA,
    [MODULES.CHECADAS_CRUDAS]: ACCESS_LEVELS.NINGUNO,
    [MODULES.INCIDENCIAS]: ACCESS_LEVELS.AREA,
    [MODULES.REPORTES]: ACCESS_LEVELS.AREA,
    [MODULES.DISPOSITIVOS]: ACCESS_LEVELS.NINGUNO,
    [MODULES.HORARIOS]: ACCESS_LEVELS.NINGUNO,
    [MODULES.USUARIOS_SISTEMA]: ACCESS_LEVELS.NINGUNO,
    [MODULES.AUDITORIA]: ACCESS_LEVELS.NINGUNO,
    [MODULES.CONFIGURACION]: ACCESS_LEVELS.NINGUNO,
  },

  [ROLES.EMPLEADO]: {
    [MODULES.DASHBOARD]: ACCESS_LEVELS.NINGUNO,
    [MODULES.EMPLEADOS]: ACCESS_LEVELS.NINGUNO,
    [MODULES.ASISTENCIA]: ACCESS_LEVELS.PROPIO,
    [MODULES.CHECADAS_CRUDAS]: ACCESS_LEVELS.NINGUNO,
    [MODULES.INCIDENCIAS]: ACCESS_LEVELS.PROPIO,
    [MODULES.REPORTES]: ACCESS_LEVELS.PROPIO,
    [MODULES.DISPOSITIVOS]: ACCESS_LEVELS.NINGUNO,
    [MODULES.HORARIOS]: ACCESS_LEVELS.NINGUNO,
    [MODULES.USUARIOS_SISTEMA]: ACCESS_LEVELS.NINGUNO,
    [MODULES.AUDITORIA]: ACCESS_LEVELS.NINGUNO,
    [MODULES.CONFIGURACION]: ACCESS_LEVELS.NINGUNO,
  },

  [ROLES.AUDITOR]: {
    [MODULES.DASHBOARD]: ACCESS_LEVELS.LECTURA,
    [MODULES.EMPLEADOS]: ACCESS_LEVELS.LECTURA,
    [MODULES.ASISTENCIA]: ACCESS_LEVELS.LECTURA,
    [MODULES.CHECADAS_CRUDAS]: ACCESS_LEVELS.LECTURA,
    [MODULES.INCIDENCIAS]: ACCESS_LEVELS.LECTURA,
    [MODULES.REPORTES]: ACCESS_LEVELS.LECTURA,
    [MODULES.DISPOSITIVOS]: ACCESS_LEVELS.NINGUNO,
    [MODULES.HORARIOS]: ACCESS_LEVELS.LECTURA,
    [MODULES.USUARIOS_SISTEMA]: ACCESS_LEVELS.NINGUNO,
    [MODULES.AUDITORIA]: ACCESS_LEVELS.LECTURA,
    [MODULES.CONFIGURACION]: ACCESS_LEVELS.NINGUNO,
  },
});